type AssessmentQuestion = {
  id: string;
  prompt: string;
  options: string[];
  correctIndex: number;
  section?: string;
};

type Row = [id: string, prompt: string, options: string[], correct: number];

function pack(section: string, rows: Row[]): AssessmentQuestion[] {
  return rows.map(([id, prompt, options, correctIndex]) => ({
    id,
    prompt,
    options,
    correctIndex,
    section,
  }));
}

export const C_QUESTIONS = pack("C", [
  ["c-1", "Which header is needed for `printf`?", ["stdlib.h", "stdio.h", "string.h", "math.h"], 1],
  ["c-2", "`int` typically stores:", ["characters only", "integers", "floats only", "pointers only"], 1],
  ["c-3", "Array index starts at:", ["1", "0", "-1", "2"], 1],
  ["c-4", "`&x` means:", ["value of x", "address of x", "pointer type", "sizeof x"], 1],
  ["c-5", "`*p` on a pointer:", ["address", "dereferenced value", "size", "type"], 1],
  ["c-6", "`NULL` is used for:", ["ints", "invalid/empty pointer", "floats", "chars"], 1],
  ["c-7", "`sizeof(char)` is:", ["2", "1", "4", "8"], 1],
  ["c-8", "String in C is:", ["String class", "char array with '\\0'", "list", "JSON"], 1],
  ["c-9", "`malloc` is in:", ["stdio.h", "stdlib.h", "math.h", "ctype.h"], 1],
  ["c-10", "After `malloc` you should:", ["ignore", "free when done", "printf only", "never free"], 1],
  ["c-11", "`for(;;)` is:", ["syntax error", "infinite loop", "runs once", "skips"], 1],
  ["c-12", "`switch` needs:", ["only if", "case labels", "class", "goto only"], 1],
  ["c-13", "`++i` vs `i++` as statement:", ["always different", "same effect on i", "illegal", "i unchanged"], 1],
  ["c-14", "`struct` groups:", ["functions only", "related data fields", "files", "threads"], 1],
  ["c-15", "File pointer type is:", ["int", "FILE*", "char", "void"], 1],
  ["c-16", "`const int *p` means:", ["p is const", "pointee is const int", "p is int", "nothing"], 1],
  ["c-17", "Undefined behavior example:", ["printf(\"%d\", 1)", "use after free", "return 0", "int x=0"], 1],
  ["c-18", "`#include` is handled by:", ["linker", "preprocessor", "CPU", "OS kernel"], 1],
  ["c-19", "`static` local variable:", ["new each call", "persists across calls", "global always", "register"], 1],
  ["c-20", "Main return type in hosted C:", ["void required", "int", "char", "float"], 1],
  ["c-21", "`strcmp` equal strings return:", ["1", "0", "-1", "NULL"], 1],
  ["c-22", "A segfault often means:", ["syntax error", "invalid memory access", "slow loop", "unused var"], 1],
  ["c-23", "`enum` is:", ["float set", "named integer constants", "string map", "thread"], 1],
  ["c-24", "Pass-by in C functions:", ["always copy of pointer value / by value", "by class", "by name only", "by SQL"], 0],
  ["c-25", "`break` in loop:", ["skips one", "exits innermost loop", "exits program", "returns 1"], 1],
]);

export const CPP_QUESTIONS = pack("C++", [
  ["cpp-1", "`cout` lives in:", ["stdio", "iostream", "math", "vector"], 1],
  ["cpp-2", "`new` returns:", ["stack int", "heap allocation", "register", "file"], 1],
  ["cpp-3", "`delete` pairs with:", ["malloc", "new", "alloca", "fopen"], 1],
  ["cpp-4", "A class default access is:", ["public", "private", "protected", "export"], 1],
  ["cpp-5", "`virtual` enables:", ["macros", "runtime polymorphism", "linking", "GPU"], 1],
  ["cpp-6", "`std::vector` is:", ["linked list", "dynamic array", "tree", "hash map"], 1],
  ["cpp-7", "`std::map` is typically:", ["unsorted list", "ordered key/value", "stack", "queue"], 1],
  ["cpp-8", "RAII means:", ["raw arrays", "resource tied to object lifetime", "recursion", "JIT"], 1],
  ["cpp-9", "`nullptr` is:", ["NULL macro only", "null pointer constant", "0.0", "false bool"], 1],
  ["cpp-10", "`const` method cannot:", ["be called", "modify members (except mutable)", "return", "exist"], 1],
  ["cpp-11", "Reference `&` must:", ["be null", "be bound when created", "resize", "be heap"], 1],
  ["cpp-12", "`template` is:", ["runtime only", "compile-time generic", "SQL", "GPU shader"], 1],
  ["cpp-13", "STL algorithms are in:", ["<algo.h>", "<algorithm>", "<stdio.h>", "<net>"], 1],
  ["cpp-14", "`override` checks:", ["linker", "virtual override correctness", "CPU", "cache"], 1],
  ["cpp-15", "Move semantics use:", ["copy only", "rvalue references", "goto", "eval"], 1],
  ["cpp-16", "`unique_ptr` is:", ["shared", "exclusive ownership", "raw C pointer", "stack int"], 1],
  ["cpp-17", "`shared_ptr` uses:", ["no count", "reference count", "malloc only", "GC pause always"], 1],
  ["cpp-18", "Exception handling keywords:", ["try/catch", "rescue", "except", "trap"], 0],
  ["cpp-19", "`namespace` avoids:", ["loops", "name clashes", "RAM", "IO"], 1],
  ["cpp-20", "`auto` deduces:", ["nothing", "type from initializer", "only int", "linkage"], 1],
  ["cpp-21", "Header guards prevent:", ["IO", "multiple inclusion", "inlining", "RTTI"], 1],
  ["cpp-22", "`this` pointer is:", ["global", "pointer to current object", "stack size", "vtable only"], 1],
  ["cpp-23", "Destructor name is:", ["~ClassName", "delete Class", "free", "dispose"], 0],
  ["cpp-24", "`std::string` is:", ["C string only", "C++ string class", "int alias", "FILE"], 1],
  ["cpp-25", "Undefined behavior in C++:", ["std::cout", "use after free", "return 0", "include iostream"], 1],
]);

export const TYPESCRIPT_QUESTIONS = pack("TypeScript", [
  ["ts-1", "TypeScript compiles to:", ["Java", "JavaScript", "C", "SQL"], 1],
  ["ts-2", "`interface` describes:", ["runtime class only", "object shape", "CSS", "SQL table"], 1],
  ["ts-3", "`any` means:", ["number only", "opt-out of checking", "never", "void"], 1],
  ["ts-4", "`unknown` is:", ["same as any", "safer any — must narrow", "never", "string"], 1],
  ["ts-5", "Union type uses:", ["&", "|", "+", "*"], 1],
  ["ts-6", "`type` alias can:", ["only classes", "name a union/object", "start the JVM", "query DB"], 1],
  ["ts-7", "`readonly` property:", ["writable", "cannot reassign after init", "private", "static"], 1],
  ["ts-8", "Generics use:", ["<>", "{}", "[] only", "%%"], 0],
  ["ts-9", "`as const` makes:", ["mutable", "narrow literal types", "any", "JSX"], 1],
  ["ts-10", "`enum` in TS:", ["CSS", "named constants", "SQL join", "thread"], 1],
  ["ts-11", "`?.` is:", ["multiply", "optional chaining", "spread", "rest"], 1],
  ["ts-12", "`??` is:", ["AND", "nullish coalescing", "XOR", "pipe"], 1],
  ["ts-13", "`.d.ts` files are:", ["CSS", "type declarations", "sourcemaps", "tests"], 1],
  ["ts-14", "`never` means:", ["any", "type that never occurs", "string", "object"], 1],
  ["ts-15", "`implements` on class:", ["extends CSS", "must satisfy interface", "imports", "builds C"], 1],
  ["ts-16", "Tuple type example:", ["string", "[string, number]", "Map", "any[]"], 1],
  ["ts-17", "`keyof T` is:", ["values", "union of keys", "length", "prototype"], 1],
  ["ts-18", "tsconfig `strict` turns on:", ["prettier", "stricter checks", "webpack", "eslint only"], 1],
  ["ts-19", "`public` in constructor:", ["illegal", "declares and assigns field", "CSS", "SQL"], 1],
  ["ts-20", "JSX in TS uses:", [".js only", ".tsx", ".css", ".sql"], 1],
  ["ts-21", "`Record<K,V>` is:", ["array", "object map type", "promise", "date"], 1],
  ["ts-22", "Type assertion uses:", ["==", "as Type", "instanceof only", "eval"], 1],
  ["ts-23", "`void` return means:", ["number", "no useful return", "never exits", "string"], 1],
  ["ts-24", "Structural typing means:", ["names must match", "shape compatibility", "nominal Java only", "hash"], 1],
  ["ts-25", "`Promise<T>` wraps:", ["sync T", "async future T", "array T", "map"], 1],
]);

export const HTML_QUESTIONS = pack("HTML/CSS", [
  ["html-1", "HTML stands for:", ["Hyperlinks", "HyperText Markup Language", "Home Tool", "HighText"], 1],
  ["html-2", "Largest heading is:", ["h6", "h1", "p", "title"], 1],
  ["html-3", "Link tag is:", ["<link href>", "<a href>", "<url>", "<goto>"], 1],
  ["html-4", "Image uses:", ["src", "href only", "link", "url"], 0],
  ["html-5", "CSS means:", ["Computer Style", "Cascading Style Sheets", "Creative Sheets", "Color Style"], 1],
  ["html-6", "ID selector is:", [".name", "#name", "name", "*name"], 1],
  ["html-7", "Class selector is:", ["#name", ".name", "@name", "name:"], 1],
  ["html-8", "`display:flex` is for:", ["print only", "layout", "fonts", "SEO"], 1],
  ["html-9", "Box model includes:", ["only content", "content+padding+border+margin", "CPU", "DNS"], 1],
  ["html-10", "`position:absolute` is relative to:", ["always viewport", "nearest positioned ancestor", "html only", "body font"], 1],
  ["html-11", "Semantic tag example:", ["<div>", "<article>", "<span>", "<b>"], 1],
  ["html-12", "Form submit default method:", ["PUT", "GET", "PATCH", "WS"], 1],
  ["html-13", "`alt` on img is for:", ["CSS", "accessibility / fallback", "SEO only JS", "cache"], 1],
  ["html-14", "Media query is used for:", ["SQL", "responsive CSS", "JWT", "DNS"], 1],
  ["html-15", "`z-index` affects:", ["font size", "stacking order", "network", "SEO title"], 1],
  ["html-16", "Flex main axis default:", ["column", "row", "grid", "none"], 1],
  ["html-17", "`<input type=\"email\">` helps:", ["CPU", "validation / keyboard", "SQL", "TLS"], 1],
  ["html-18", "CSS grid uses:", ["tables only", "rows and columns", "floats only", "frames"], 1],
  ["html-19", "`rem` is relative to:", ["parent px only", "root font size", "viewport always", "image"], 1],
  ["html-20", "`<script defer>` means:", ["block parse", "download, run after parse", "never run", "CSS"], 1],
  ["html-21", "Contrast in a11y is about:", ["JS heap", "text vs background", "SQL", "CDN"], 1],
  ["html-22", "`<label for>` ties to:", ["CSS id", "input id", "class", "href"], 1],
  ["html-23", "Specificity of ID is:", ["lowest", "higher than class", "same as element", "zero"], 1],
  ["html-24", "`overflow:hidden` clips:", ["network", "overflowing content", "JS errors", "cookies"], 1],
  ["html-25", "ARIA is for:", ["animations", "accessibility roles", "routing", "bundling"], 1],
]);

export const PHP_QUESTIONS = pack("PHP", [
  ["php-1", "PHP files usually end with:", [".js", ".php", ".py", ".java"], 1],
  ["php-2", "Variables start with:", ["@", "$", "#", "&"], 1],
  ["php-3", "`echo` is used to:", ["query SQL", "output text", "define class", "hash"], 1],
  ["php-4", "Arrays use:", ["{}", "[] / array()", "<>", "||"], 1],
  ["php-5", "`===` compares:", ["value only", "value and type", "hash", "length"], 1],
  ["php-6", "`$_GET` is:", ["cookies", "query string data", "session only", "files"], 1],
  ["php-7", "`$_POST` is:", ["URL query", "request body form data", "headers only", "CLI"], 1],
  ["php-8", "`isset` checks:", ["type", "variable is set/not null", "SQL", "file"], 1],
  ["php-9", "PDO is used for:", ["CSS", "database access", "templates only", "queues"], 1],
  ["php-10", "To prevent SQL injection:", ["echo SQL", "prepared statements", "eval", "extract"], 1],
  ["php-11", "`session_start` is for:", ["CSS", "sessions", "composer", "opcache"], 1],
  ["php-12", "Composer manages:", ["nginx", "PHP packages", "MySQL server", "DNS"], 1],
  ["php-13", "`include` vs `require`:", ["same always", "require fatals if missing", "include fatals", "neither loads"], 1],
  ["php-14", "`->` accesses:", ["static", "object property/method", "global", "namespace"], 1],
  ["php-15", "`::` is:", ["object", "static/class access", "concat", "and"], 1],
  ["php-16", "String concat operator:", ["+", ".", "&", "|"], 1],
  ["php-17", "`foreach` loops:", ["ints only", "arrays/iterables", "files only", "SQL"], 1],
  ["php-18", "`password_hash` is for:", ["SQL", "storing passwords", "sessions", "CORS"], 1],
  ["php-19", "PHP is mainly:", ["browser GPU", "server-side", "CSS", "assembly"], 1],
  ["php-20", "`json_encode` returns:", ["array", "JSON string", "XML", "int"], 1],
  ["php-21", "`try/catch` handles:", ["CSS", "exceptions", "nginx", "DNS"], 1],
  ["php-22", "`public` on method:", ["private", "callable from outside", "SQL", "CLI only"], 1],
  ["php-23", "`count($arr)` returns:", ["hash", "number of elements", "max", "sum"], 1],
  ["php-24", "Superglobals include:", ["$x only", "$_SERVER", "$this always", "$argv only"], 1],
  ["php-25", "`header('Location: ...')` does:", ["CSS", "HTTP redirect", "SQL insert", "log"], 1],
]);

export const GO_QUESTIONS = pack("Go", [
  ["go-1", "Go files end with:", [".js", ".go", ".py", ".java"], 1],
  ["go-2", "Entry is:", ["start()", "func main()", "init only", "run()"], 1],
  ["go-3", "`:=` means:", ["type assert", "short declare and assign", "pointer", "import"], 1],
  ["go-4", "Error handling often uses:", ["try/catch", "returned error values", "throws", "rescue"], 1],
  ["go-5", "A goroutine is:", ["SQL job", "lightweight thread", "class", "file"], 1],
  ["go-6", "`chan` is for:", ["CSS", "communication between goroutines", "JSON", "HTML"], 1],
  ["go-7", "`go func()` starts:", ["HTTP only", "a goroutine", "C compiler", "test"], 1],
  ["go-8", "Packages are imported with:", ["include", "import", "require", "use"], 1],
  ["go-9", "`defer` runs:", ["first", "when surrounding function returns", "never", "at compile"], 1],
  ["go-10", "Slices are:", ["fixed arrays only", "dynamic views over arrays", "maps", "channels"], 1],
  ["go-11", "`map[string]int` is:", ["list", "hash map", "set of structs", "file"], 1],
  ["go-12", "`make` can create:", ["classes", "slice/map/chan", "interfaces only", "SQL"], 1],
  ["go-13", "Exported name starts with:", ["underscore", "uppercase", "pkg.", "$"], 1],
  ["go-14", "`interface{}` in old Go is:", ["int", "empty interface / any", "string", "error"], 1],
  ["go-15", "`go.mod` is for:", ["CSS", "module/dependencies", "nginx", "docker only"], 1],
  ["go-16", "Pointers use:", ["& and *", "-> only", "::", "."], 0],
  ["go-17", "`range` loops:", ["only ints", "slices/maps/chans", "files only", "SQL"], 1],
  ["go-18", "Zero value of pointer is:", ["0", "nil", "false", "\"\""], 1],
  ["go-19", "`select` on chans is like:", ["SQL select", "switch on channel ops", "CSS", "HTTP"], 1],
  ["go-20", "Race detector finds:", ["CSS", "data races", "404s", "SQL"], 1],
  ["go-21", "`context` is for:", ["styling", "deadlines/cancelation", "ORM only", "GPU"], 1],
  ["go-22", "Tests live in:", ["_test.go", ".spec.js", "Test.java", "test.php"], 0],
  ["go-23", "`append` grows:", ["maps", "slices", "structs", "ints"], 1],
  ["go-24", "Multiple return values:", ["illegal", "idiomatic", "only in C", "CSS"], 1],
  ["go-25", "`go fmt` does:", ["build", "format code", "deploy", "lint SQL"], 1],
]);
