import type { AssessmentQuestion } from "@/lib/assessment/catalog";

type Row = [id: string, prompt: string, options: string[], correct: number];

function pack(section: string, rows: Row[]): AssessmentQuestion[] {
  return rows.map(([id, prompt, options, correctIndex]) => ({
    id,
    prompt,
    options,
    correctIndex,
    section,
  }));
}

export const PYTHON_QUESTIONS = pack("Python", [
  ["py-1", "What is the output of `len([1, 2, 3])`?", ["2", "3", "4", "Error"], 1],
  ["py-2", "Which keyword defines a function?", ["func", "def", "function", "lambda"], 1],
  ["py-3", "What type is `{\"a\": 1}`?", ["List", "Tuple", "Dictionary", "Set"], 2],
  ["py-4", "Lists in Python are:", ["Immutable", "Mutable", "Always sorted", "Fixed size"], 1],
  ["py-5", "`list(range(3))` is:", ["[1,2,3]", "[0,1,2]", "[0,1,2,3]", "error"], 1],
  ["py-6", "Which creates a tuple?", ["[1,2]", "(1,2)", "{1,2}", "{1:2}"], 1],
  ["py-7", "`True and False` evaluates to:", ["True", "False", "None", "Error"], 1],
  ["py-8", "How do you start a comment?", ["//", "#", "/*", "--"], 1],
  ["py-9", "`int(\"10\")` returns:", ["\"10\"", "10", "10.0", "Error"], 1],
  ["py-10", "Which is a set?", ["(1,2)", "[1,2]", "{1, 2}", "{1:2}"], 2],
  ["py-11", "`\"hi\" * 2` is:", ["hihi", "hi2", "error", "hi hi"], 0],
  ["py-12", "Default value of `print` end is:", ["space", "newline", "tab", "empty"], 1],
  ["py-13", "`None` is:", ["0", "False", "a singleton null", "empty string"], 2],
  ["py-14", "To handle errors use:", ["catch", "try/except", "rescue", "throws"], 1],
  ["py-15", "`len(\"abc\")` is:", ["2", "3", "4", "1"], 1],
  ["py-16", "List index of first item is:", ["1", "0", "-1", "None"], 1],
  ["py-17", "`bool([])` is:", ["True", "False", "None", "Error"], 1],
  ["py-18", "Which opens a file for reading?", ["open(f,\"w\")", "open(f,\"r\")", "read(f)", "file.r"], 1],
  ["py-19", "`==` compares:", ["identity", "equality of value", "types only", "memory size"], 1],
  ["py-20", "`is` compares:", ["values", "object identity", "hashes", "lengths"], 1],
  ["py-21", "A generator uses:", ["return only", "yield", "goto", "async only"], 1],
  ["py-22", "`[x*x for x in range(3)]` is:", ["[0,1,4]", "[1,4,9]", "[0,1,2]", "error"], 0],
  ["py-23", "PIP is used to:", ["compile", "install packages", "debug", "format"], 1],
  ["py-24", "`dict.get(\"x\", 0)` if missing returns:", ["None", "0", "error", "\"x\""], 1],
  ["py-25", "PEP 8 is about:", ["speed", "style", "security", "packaging only"], 1],
  ["py-26", "`sorted([3,1,2])` is:", ["[3,1,2]", "[1,2,3]", "[3,2,1]", "None"], 1],
  ["py-27", "A class method first arg is usually:", ["this", "self", "cls always", "me"], 1],
  ["py-28", "`__init__` is:", ["destructor", "constructor", "import hook", "main"], 1],
  ["py-29", "Virtual env is for:", ["GPU", "isolated packages", "GUI", "testing network"], 1],
  ["py-30", "`break` exits:", ["function", "innermost loop", "program", "module"], 1],
  ["py-31", "`continue` does:", ["quit loop", "next iteration", "restart program", "skip file"], 1],
  ["py-32", "`lambda x: x+1` is:", ["class", "anonymous function", "module", "decorator"], 1],
  ["py-33", "`*args` collects:", ["keywords", "extra positional args", "only lists", "globals"], 1],
  ["py-34", "`**kwargs` collects:", ["positionals", "keyword args", "imports", "types"], 1],
  ["py-35", "Mutable default args are:", ["recommended", "a common bug source", "required", "faster"], 1],
  ["py-36", "`with open(...) as f` ensures:", ["faster IO", "file is closed", "encryption", "async"], 1],
  ["py-37", "NumPy arrays are typically:", ["linked lists", "homogeneous numeric arrays", "JSON", "strings"], 1],
  ["py-38", "`isinstance(3, int)` is:", ["False", "True", "None", "Error"], 1],
  ["py-39", "The REPL is:", ["a compiler flag", "interactive shell", "package", "linter"], 1],
  ["py-40", "`hash([])` :", ["works", "raises TypeError", "returns 0", "returns []"], 1],
  ["py-41", "GIL mainly affects:", ["I/O bound threads CPU parallelism", "CPU-bound threads", "async only", "imports"], 1],
  ["py-42", "`from x import *` is:", ["best practice", "often discouraged", "required", "faster always"], 1],
  ["py-43", "A decorator is:", ["a loop", "a function wrapping a function", "a class only", "a file"], 1],
  ["py-44", "`zip([1,2],[3,4])` first pair is:", ["(1,2)", "(1,3)", "(2,4)", "error"], 1],
  ["py-45", "`enumerate(['a','b'])` first item:", ["(0,'a')", "(1,'a')", "'a'", "0"], 0],
  ["py-46", "f-strings start with:", ["s", "f", "r only", "%"], 1],
  ["py-47", "`set([1,1,2])` size:", ["3", "2", "1", "0"], 1],
  ["py-48", "To copy a list shallowly:", ["a=b", "a=b[:]", "a=copy.deepcopy only", "a=list"], 1],
  ["py-49", "`pass` is:", ["exit", "no-op placeholder", "continue", "return 0"], 1],
  ["py-50", "`__name__ == \"__main__\"` means:", ["imported as lib", "run as script", "test failed", "compiled"], 1],
]);

export const JAVA_QUESTIONS = pack("Java", [
  ["jv-1", "Keyword to inherit a class?", ["implements", "extends", "inherits", "super"], 1],
  ["jv-2", "Size of `int`?", ["16 bits", "32 bits", "64 bits", "OS dependent"], 1],
  ["jv-3", "No duplicates:", ["ArrayList", "LinkedList", "HashSet", "Stack"], 2],
  ["jv-4", "JVM stands for:", ["Java Variable Machine", "Java Virtual Machine", "Just Virtual Memory", "Java Vendor Module"], 1],
  ["jv-5", "Entry method is:", ["start()", "main", "init", "run"], 1],
  ["jv-6", "`String` is:", ["primitive", "immutable object", "mutable array", "int alias"], 1],
  ["jv-7", "`==` on two new String(\"a\") compares:", ["chars", "references", "hash only", "length"], 1],
  ["jv-8", "`equals` on String compares:", ["identity only", "character content", "hashCode only", "class name"], 1],
  ["jv-9", "Interface methods are by default:", ["private", "public", "protected", "package"], 1],
  ["jv-10", "`final` class cannot be:", ["instantiated", "extended", "imported", "compiled"], 1],
  ["jv-11", "`static` member belongs to:", ["instance", "class", "package", "thread"], 1],
  ["jv-12", "Checked exception example:", ["NullPointerException", "IOException", "ArithmeticException", "Error"], 1],
  ["jv-13", "`ArrayList` vs array:", ["fixed size vs growable", "growable vs often fixed array", "same", "slower always"], 1],
  ["jv-14", "Package keyword:", ["import", "package", "module", "include"], 1],
  ["jv-15", "`super()` calls:", ["static block", "parent constructor", "main", "GC"], 1],
  ["jv-16", "Overloading is:", ["same signature", "same name different params", "two classes", "JNI"], 1],
  ["jv-17", "Overriding needs:", ["same name and params in subclass", "new name", "static only", "private only"], 0],
  ["jv-18", "`this` refers to:", ["class", "current instance", "parent", "thread"], 1],
  ["jv-19", "Bytecode file extension:", [".java", ".class", ".jar only", ".exe"], 1],
  ["jv-20", "Garbage collection reclaims:", ["stack frames only", "unreachable objects", "files", "CPU"], 1],
  ["jv-21", "`synchronized` is for:", ["IO speed", "thread mutual exclusion", "generics", "UI"], 1],
  ["jv-22", "Java is primarily:", ["pass by reference objects as refs, primitives by value", "always copy objects", "macros", "unsigned only"], 0],
  ["jv-23", "`HashMap` allows:", ["duplicate keys", "one null key (typically)", "only strings", "sorted keys always"], 1],
  ["jv-24", "`TreeMap` is:", ["unsorted", "sorted by keys", "a list", "a set of ints"], 1],
  ["jv-25", "Access most restrictive:", ["public", "protected", "private", "default"], 2],
  ["jv-26", "`abstract` class:", ["can be new'ed", "cannot be instantiated", "must be final", "has no methods"], 1],
  ["jv-27", "Multiple inheritance of classes:", ["allowed", "not allowed (classes)", "only via int", "via goto"], 1],
  ["jv-28", "`implements` is for:", ["classes", "interfaces", "enums only", "records only"], 1],
  ["jv-29", "Autoboxing converts:", ["int to Integer", "String to int", "file to stream", "thread to task"], 0],
  ["jv-30", "`finally` runs:", ["only on success", "after try/catch almost always", "never with return", "only on Error"], 1],
  ["jv-31", "JRE includes:", ["compiler javac only", "JVM + libraries to run", "IDE", "Maven"], 1],
  ["jv-32", "JDK includes:", ["JRE + compiler tools", "browser", "OS", "DB"], 0],
  ["jv-33", "`volatile` is about:", ["disk", "visibility across threads", "GC speed", "generics"], 1],
  ["jv-34", "Generic `List<String>` prevents:", ["runtime add of Integer (compile time)", "all errors", "IO", "null"], 0],
  ["jv-35", "`Optional` is for:", ["required ints", "possibly absent values", "threads", "dates only"], 1],
  ["jv-36", "Stream `map` does:", ["filter", "transform elements", "sort disk", "join SQL"], 1],
  ["jv-37", "`record` (modern Java) is for:", ["mutable beans only", "immutable data carriers", "JNI", "applets"], 1],
  ["jv-38", "Default interface method:", ["Java 7", "can have a body", "must be static", "is private only"], 1],
  ["jv-39", "`enum` can:", ["extend a class", "have fields and methods", "be primitive", "replace JVM"], 1],
  ["jv-40", "Checked exceptions must be:", ["ignored", "declared or caught", "unsigned", "final"], 1],
  ["jv-41", "`StringBuilder` is:", ["immutable", "mutable, not synced", "synced like Vector", "a Map"], 1],
  ["jv-42", "`StringBuffer` is:", ["immutable", "mutable and synchronized", "a Set", "faster always than Builder"], 1],
  ["jv-43", "Annotation starts with:", ["#", "@", "$", "%"], 1],
  ["jv-44", "`classpath` is used to:", ["find classes/jars", "set RAM", "set CPU", "format code"], 0],
  ["jv-45", "`==` on Integer 128 vs 128 may:", ["always true", "not use cache, can be false", "not compile", "NPE"], 1],
  ["jv-46", "Marker interface has:", ["many methods", "no methods", "only static", "main"], 1],
  ["jv-47", "`wait()` is declared on:", ["Thread only", "Object", "String", "System"], 1],
  ["jv-48", "Deadlock needs:", ["one lock", "circular wait on locks", "GC", "JIT off"], 1],
  ["jv-49", "`transient` fields:", ["are serialized", "skip default serialization", "are volatile", "are static"], 1],
  ["jv-50", "SQL in JDBC starts by:", ["new Socket", "loading driver / DataSource", "fork", "eval"], 1],
]);

export const JAVASCRIPT_QUESTIONS = pack("JavaScript", [
  ["js-1", "`let` and `const` are:", ["function scoped only", "block scoped", "global only", "labels"], 1],
  ["js-2", "`===` is:", ["assignment", "loose equality", "strict equality", "spread"], 2],
  ["js-3", "Add to end of array:", ["push", "pop", "shift", "unshift"], 0],
  ["js-4", "`JSON.parse` returns:", ["string always", "a JS value", "Promise", "HTML"], 1],
  ["js-5", "`typeof null` is:", ["null", "object", "undefined", "number"], 1],
  ["js-6", "`NaN === NaN` is:", ["true", "false", "throws", "undefined"], 1],
  ["js-7", "Promise states include:", ["open", "pending/fulfilled/rejected", "locked", "idle"], 1],
  ["js-8", "`async` function returns:", ["void", "a Promise", "a thread", "a file"], 1],
  ["js-9", "`await` pauses:", ["the process", "the async function", "the GPU", "CSS"], 1],
  ["js-10", "Closures capture:", ["only globals", "outer lexical environment", "CPU", "DOM always"], 1],
  ["js-11", "`var` is:", ["block scoped", "function scoped", "const", "typed"], 1],
  ["js-12", "Arrow functions have:", ["own this", "lexical this", "super always", "arguments object same as function"], 1],
  ["js-13", "`[...arr]` is:", ["rest params", "spread copy", "bind", "reduce"], 1],
  ["js-14", "`Array.map` returns:", ["undefined", "a new array", "the same array mutated", "a Set"], 1],
  ["js-15", "`Array.filter` keeps items where callback is:", ["0", "truthy", "NaN", "null"], 1],
  ["js-16", "Event bubbling goes:", ["child to parent", "parent to child only", "to GPU", "to CSS"], 0],
  ["js-17", "`localStorage` stores:", ["functions", "strings", "classes", "sockets"], 1],
  ["js-18", "`const obj = {}; obj.x=1` :", ["throws", "allowed (object mutation)", "freezes", "deletes obj"], 1],
  ["js-19", "`Object.freeze` makes:", ["deep immutable always", "shallow freeze", "faster JSON", "a Proxy"], 1],
  ["js-20", "`==` with `\"5\" == 5` is:", ["false", "true", "error", "NaN"], 1],
  ["js-21", "Hoisting applies to:", ["let TDZ", "`var` declarations", "class fields only", "CSS"], 1],
  ["js-22", "`this` in a method (non-arrow) depends on:", ["definition site only", "call site", "file name", "strict never"], 1],
  ["js-23", "`module.exports` is:", ["ESM", "CommonJS", "CSS", "HTML"], 1],
  ["js-24", "`import`/`export` is:", ["CommonJS", "ES modules", "JSONP", "CGI"], 1],
  ["js-25", "`setTimeout(fn,0)` runs:", ["immediately before anything", "after current stack, macrotask", "on GPU", "never"], 1],
  ["js-26", "Microtasks include:", ["setTimeout", "Promise.then", "alert", "page load only"], 1],
  ["js-27", "`document.querySelector` returns:", ["NodeList always", "first match or null", "array", "jQuery"], 1],
  ["js-28", "`preventDefault` is for:", ["stopping default action", "removing node", "CORS", "minify"], 0],
  ["js-29", "`fetch` returns:", ["JSON", "a Promise", "string", "XML always"], 1],
  ["js-30", "`JSON.stringify(undefined)` in object:", ["keeps key", "omits the key", "throws", "null string"], 1],
  ["js-31", "Optional chaining is:", ["?.", "??", "...", "##"], 0],
  ["js-32", "Nullish coalescing `??` treats as missing:", ["0", "null/undefined", "\"\"", "false"], 1],
  ["js-33", "`Map` keys can be:", ["only strings", "any value", "only numbers", "only objects"], 1],
  ["js-34", "`Set` stores:", ["duplicates", "unique values", "pairs", "DOM only"], 1],
  ["js-35", "`for...of` iterates:", ["object keys only", "iterable values", "CSS rules", "HTTP"], 1],
  ["js-36", "`for...in` iterates:", ["array indexes / enumerable keys", "Map values", "Promises", "bytes"], 0],
  ["js-37", "Strict mode is enabled by:", ["\"use strict\"", "#strict", "use.strict()", "with"], 0],
  ["js-38", "`typeof function` is:", ["object", "function", "method", "lambda"], 1],
  ["js-39", "Debounce is used to:", ["delay until quiet", "retry HTTP", "compress", "hash"], 0],
  ["js-40", "`event.target` is:", ["listener element always", "originating element", "window", "body"], 1],
  ["js-41", "`innerHTML` vs `textContent`:", ["same XSS", "innerHTML parses HTML", "textContent parses HTML", "both execute script always"], 1],
  ["js-42", "`history.pushState` changes:", ["full reload always", "URL without full reload", "cookies", "TLS"], 1],
  ["js-43", "`CORS` is enforced by:", ["the database", "browsers on cross-origin requests", "CSS", "JSON"], 1],
  ["js-44", "`npm` is:", ["a language", "a package manager", "a browser", "a DB"], 1],
  ["js-45", "`node` runs:", ["only browsers", "JS on the server", "Java bytecode", "SQL"], 1],
  ["js-46", "`prototype` is used for:", ["CSS", "inheritance on objects", "HTTP/2", "dates only"], 1],
  ["js-47", "`class` syntax is:", ["not sugar over prototypes", "syntactic sugar over prototypes", "Java interop", "a new VM"], 1],
  ["js-48", "`WeakMap` keys must be:", ["strings", "objects", "numbers", "booleans"], 1],
  ["js-49", "`structuredClone` does:", ["JSON roundtrip only", "deep clone many types", "shallow copy", "hash"], 1],
  ["js-50", "`AbortController` is for:", ["canceling fetch", "CSS", "SQL", "fonts"], 0],
]);

export const SQL_QUESTIONS = pack("SQL", [
  ["sql-1", "Read rows with:", ["GET", "SELECT", "FETCH", "READ"], 1],
  ["sql-2", "Filter rows with:", ["ORDER BY", "GROUP BY", "WHERE", "LIMIT only"], 2],
  ["sql-3", "JOIN combines:", ["rows from tables", "servers", "users", "indexes only"], 0],
  ["sql-4", "Remove duplicate result rows:", ["UNIQUE", "DISTINCT", "DIFFERENT", "ONLY"], 1],
  ["sql-5", "Sort results:", ["WHERE", "ORDER BY", "HAVING", "JOIN"], 1],
  ["sql-6", "Filter groups:", ["WHERE", "HAVING", "FROM", "SELECT"], 1],
  ["sql-7", "`COUNT(*)` counts:", ["nulls in one col", "rows", "tables", "indexes"], 1],
  ["sql-8", "`PRIMARY KEY` is:", ["nullable duplicates ok", "unique not null", "always text", "a JOIN"], 1],
  ["sql-9", "`FOREIGN KEY` references:", ["same row always", "another table's key", "the OS", "JSON"], 1],
  ["sql-10", "`INNER JOIN` returns:", ["all left rows", "matching rows", "all right only", "cartesian always"], 1],
  ["sql-11", "`LEFT JOIN` keeps:", ["only matches", "all left rows", "all right only", "none"], 1],
  ["sql-12", "`NULL = NULL` in WHERE is:", ["TRUE", "UNKNOWN/false for match", "1", "error always"], 1],
  ["sql-13", "`IS NULL` tests:", ["empty string", "NULL", "0", "false"], 1],
  ["sql-14", "`BETWEEN 1 AND 5` is:", ["exclusive", "inclusive typically", "strings only", "joins"], 1],
  ["sql-15", "`LIKE '%a'` matches:", ["starts with a", "ends with a", "equals a", "null"], 1],
  ["sql-16", "`IN (1,2,3)` is:", ["a join", "membership test", "index hint", "DDL"], 1],
  ["sql-17", "`GROUP BY` is used with:", ["aggregates", "INSERT", "GRANT", "VACUUM"], 0],
  ["sql-18", "`AVG` ignores:", ["numbers", "NULL in many engines", "zero", "ones"], 1],
  ["sql-19", "DDL example:", ["SELECT", "CREATE TABLE", "COMMIT", "GRANT only DCL"], 1],
  ["sql-20", "DML example:", ["CREATE", "INSERT", "GRANT", "TRUNCATE is DDL-ish"], 1],
  ["sql-21", "`COMMIT` ends:", ["a query plan", "a transaction", "a backup", "an index"], 1],
  ["sql-22", "`ROLLBACK` undoes:", ["committed work", "uncommitted transaction", "the schema forever", "users"], 1],
  ["sql-23", "Index speeds:", ["writes always", "lookups on indexed cols", "network", "CSS"], 1],
  ["sql-24", "`UNIQUE` constraint:", ["allows dups", "disallows duplicate values", "sorts", "joins"], 1],
  ["sql-25", "`CHECK` constraint:", ["indexes", "validates a condition", "replicates", "backs up"], 1],
  ["sql-26", "`VIEW` is:", ["always a table copy", "a stored query", "a user", "a lock"], 1],
  ["sql-27", "`UNION` vs `UNION ALL`:", ["ALL removes dups", "UNION removes dups", "same", "ALL is slower always"], 1],
  ["sql-28", "Subquery is:", ["a trigger", "query nested in query", "an index", "a user"], 1],
  ["sql-29", "`EXISTS` checks:", ["file exists", "whether subquery returns a row", "column type", "RAM"], 1],
  ["sql-30", "`CASE` is for:", ["loops", "conditional expressions", "cursors only", "users"], 1],
  ["sql-31", "`COALESCE(a,b)` returns:", ["sum", "first non-null", "max", "concat"], 1],
  ["sql-32", "`CAST` / `::` is:", ["join", "type conversion", "index", "lock"], 1],
  ["sql-33", "Normalization reduces:", ["joins", "redundancy", "keys", "SQL"], 1],
  ["sql-34", "1NF requires:", ["repeating groups", "atomic values", "3 tables", "no keys"], 1],
  ["sql-35", "`DELETE` without WHERE:", ["deletes one row", "deletes all rows", "drops table", "no-op"], 1],
  ["sql-36", "`TRUNCATE` typically:", ["row-by-row undo like DELETE", "empties table quickly", "drops DB", "creates index"], 1],
  ["sql-37", "`ALTER TABLE` is:", ["DML", "DDL", "TCL", "DQL only"], 1],
  ["sql-38", "`GRANT` is:", ["DML", "DCL", "DDL always", "TCL"], 1],
  ["sql-39", "ACID `I` is:", ["Index", "Isolation", "Insert", "Integer"], 1],
  ["sql-40", "Isolation prevents:", ["backups", "some concurrent anomalies", "NULLs", "joins"], 1],
  ["sql-41", "`EXPLAIN` shows:", ["users", "query plan", "passwords", "UI"], 1],
  ["sql-42", "Cardinality means:", ["CPU cores", "distinct values estimate", "RAM", "timeout"], 1],
  ["sql-43", "`LIMIT 10` (MySQL) / `FETCH`:", ["sorts", "caps rows returned", "creates index", "commits"], 1],
  ["sql-44", "Window function example:", ["WHERE", "ROW_NUMBER()", "INSERT", "DROP"], 1],
  ["sql-45", "`PARTITION BY` is used in:", ["FROM only", "window functions", "GRANT", "VACUUM"], 1],
  ["sql-46", "Self join is:", ["impossible", "joining a table to itself", "UNION", "index"], 1],
  ["sql-47", "`CROSS JOIN` is:", ["inner only", "cartesian product", "left only", "anti join"], 1],
  ["sql-48", "Stored procedure is:", ["a CSS file", "server-side routine", "a browser", "JSON"], 1],
  ["sql-49", "`TRIGGER` fires:", ["on schedule only", "on table events", "on CSS", "on DNS"], 1],
  ["sql-50", "`DISTINCT ON` (Postgres) is:", ["standard MySQL", "keeps first row per expressions", "a JOIN", "a user"], 1],
]);
